---
title: "Revised Prokopius Project Proposal"
author: "Rachel Prokopius 1/10/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Research Statement:
I am a first-year graduate student at Florida International University. Before becoming a graduate student, I performed biological research as an undergraduate student at Northern Kentucky University looking to develop better methods for determining the size of macroinvertebrates in stream systems, which would then be used to predict energectic content and relative stream health. I spent three years collecting data in Northern Kentucky, USA and Karlstad, Sweden and running linear models between surface area and dry mass values to compare to the traditional length-to-dry mass relationship used in literature since the 1980's. However, certain linear plots appeared to have a nonlinear trend in the relationship between the dependent variable of dry mass (mg) and independent variables of surface area (square mm) and length (mm).

## Objectives and Hypothesis:
The objective of this project is to determine the extent to which nonlinear modeling explains the relationship between surface area and length to dry mass of stream macroinvertebrates in Northern Kentucky and Sweden. I predict that nonlinear models will better explain the relationships between variables, and of the nonlinear models the surface area models will better explain dry mass values then will length measurements.

## Methods (Data Selection and Analysis)
I will use data collected throughout my undergraduate years for this analysis. I will use the nlm function in Rstudio to fit nonlinear models to the data sets and produce Rsquared values with which to compare model fitness.


