---
title: "R Cheatsheet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Functions
array() make an array
as()
c() put into vector
cat()  prints output to console
class() kind of data in the variable (ex. interer, matrix, numeric, etc)
help(par) gives parameters for graphical representation
hist() histogram
is.list() is it a list, true or false
is.vector() is it a vector, true or false
lapply() apply function over list or vector
length() get number of obs. in variable
list() makes a list
    -get to element within a list, can use dollar sign or double brackets
ls()   search the user workspace (global environment)
ls('package:stats')[1:20] lists packages downloaded in R
ls.str() list and describe variables
plot() scatterplot
    -cex followed by number is different sized points
    -legend()adds legend to graph
    -pch followed by number is a different shaped point
rep() replicates values in x
rm() delete a variable
rnorm()  generate random variables that follow normal distribution
round() round to certain number of digits
save.image('name') saves R objects to a specific file
str() displays first line of numbers in a variable
typeof() how R is storing the data
unlist()take values out of a list and writes them out
## Operators
>= #greater than or equal to
<= # less than or equal to
== # equal to
!= # not equal to
= # make identical to
| # or
& # and

## Calculations
## need matlib library
cov(x1,x2) sample covariance
cov(matrix) variance-covariance matrix produced 
eigen() eigenvalues and eigenvectors
Ginv() inverse matrix
mean() mean of values
sqrt() square root
t() transpose matrix
qchisq() q values for chisquare
var() sample variance
 
## How to set up matrices
matrixname = matrix(data = , nrow = , ncol =)
## How to multiply matrices
matrix1 %*% matrix2
## Chisqure needs
## need matlib library
J: seq(1:total number of obs)
q values: qchisq((total number of obs - J+0.5)/total number of obs, p)
where p is number of variables (also number of columns)
where n is number of samples (also number of rows)


## Getting help 
help()
?functionwantdefinition of

